spring.application.name=auth-service

# Server port
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/home_insurance?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Hibernate dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT secret and expiration time saved as env variables.
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION} 